### ISSUE TITLE
US01 - Eu como usuário desejo me cadastrar na aplicação para ter minha própria conta.

### ISSUE THREAD

**Issue by isadoragalvaoss** [FGAUnB-REQ-GM/2021.2-PetSpotters#10]
Eu como usuário desejo me cadastrar na aplicação para ter minha própria conta.

### Tarefas

- [x] Criar tela de cadastro de usuário
- [x] Criar formulário para inserção de dados
- [x] Criar validação de e-mail

### Critérios de aceitação

- [x] O usuário não pode ter duas contas com o mesmo email
- [x] O usuário não pode colocar o campo de email inválido
- [x] Os dados cadastrados deverão ser válidos para Login

**Comment by hericklima22** [comment]
Closed at #61
