### ISSUE TITLE
US03 - Eu como usuário desejo redefinir minha senha através do meu email para redefinir a senha da minha conta.

### ISSUE THREAD

**Issue by isadoragalvaoss** [FGAUnB-REQ-GM/2021.2-PetSpotters#11]
Eu como usuário desejo redefinir minha senha através do meu email para redefinir a senha da minha conta.

### Tarefas

- [x] Criar a interface para colocar email
- [x] Enviar link para email para nova senha

### Critérios de aceitação

- [x] O usuário poderá criar uma nova senha
- [x] O usuário poderá acessar sua conta sua nova senha

**Comment by hericklima22** [comment]
Closed at #61
