### ISSUE TITLE
US06 - Eu como usuário desejo criar o perfil do meu pet para divulgar meu pet na plataforma.

### ISSUE THREAD

**Issue by art1505** [FGAUnB-REQ-GM/2021.2-PetSpotters#17]
Eu como usuário desejo criar o perfil do meu pet para divulgar meu pet na plataforma.

### Tarefas

- [x] Criar tela de exibição do perfil do pet

### Critérios de aceitação

- [x] O usuário pode ter apenas um perfil pet
- [x] O usuário pode inserir nome, raça, porte, data de nascimento e endereço do seu pet
- [x] O usuário não pode cadastrar um perfil para o pet sem o nome do pet
- [x] O usuário não pode cadastrar um perfil para o pet sem o endereço do pet

**Comment by antoniotoineto** [comment]
Criação de perfil de pet feita
