### ISSUE TITLE
US07 - Eu como usuário desejo poder editar o perfil do meu pet para não precisar criar outro perfil caso eu queria mudar algo.

### ISSUE THREAD

**Issue by art1505** [FGAUnB-REQ-GM/2021.2-PetSpotters#18]
Eu como usuário desejo poder editar o perfil do meu pet para não precisar criar outro perfil caso eu queria mudar algo.

### Tarefas

- [x] Criar tela de edição de perfil de pet
- [x] Alterar dados no back

### Critérios de aceitação

- [x] O usuário pode editar todos os dados do pet.

**Comment by antoniotoineto** [comment]
Edição de perfil de pet feita
