### ISSUE TITLE
US08 - Eu como usuário desejo poder inserir novas fotos do meu pet no meu perfil para manter fotos atualizadas do meu pet.

### ISSUE THREAD

**Issue by hericklima22** [FGAUnB-REQ-GM/2021.2-PetSpotters#20]
Eu como usuário desejo poder inserir novas fotos do meu pet no meu perfil para manter fotos atualizadas do meu pet.

### Tarefas

- [x] Criar a sistema de inserção de foto

### Critérios de aceitação

- [x] O perfil de pet pode ter apenas uma foto
- [x] O usuário pode pegar foto da sua galeria para adicionar no perfil do pet
- [x] O usuário pode tirar foto com a câmera para adicionar no perfil do pet

**Comment by antoniotoineto** [comment]
Inserção de foto no perfil de pet feita
