### ISSUE TITLE
Prioridade COORG 

### ISSUE THREAD

**Issue by antoniotoineto** [FGAUnB-REQ-GM/2021.2-PetSpotters#50]
### Instruções para issue:
* (Pode assistir a aula do professor do dia 17/03, que é explicado em mais detalhes)
* Não utilizar PMG nas prioridades do COORG, porque permite ambiguidade
* Deixar mais claro a frequência de uso e valor de negócio

**Comment by art1505** [comment]
Feito! Novos critérios de priorização adicionados, bem como sua descrição e valores atribuídos.

**Comment by antoniotoineto** [comment]
Adicionado na branch git-pages
