### ISSUE TITLE
US02 - Eu como usuário desejo acessar a aplicação com minhas credenciais para entrar na minha conta.

### ISSUE THREAD

**Issue by antoniotoineto** [FGAUnB-REQ-GM/2021.2-PetSpotters#56]
Eu como usuário desejo acessar a aplicação com minhas credenciais para entrar na minha conta.

### Tarefas

- [x] Criar botão Submit
- [x] Preparar ambiente no back-end
- [x] Mandar dados para o back-end ao clicar no botão Submit

### Critérios de aceitação

- [x] O usuário pode acessar sua conta com seu email e senha cadastrados
- [x] O sistema não deve permitir acessos com email/senha errados ou incompletos
- [x] O sistema deve mostrar uma mensagem caso as credenciais estejam erradas

**Comment by hericklima22** [comment]
Closed at #61
